# Generated by Django 5.2.6 on 2025-11-24 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_conces', '0005_carrito_compra_itemcarrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='automovil',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, help_text='Cantidad disponible en stock'),
        ),
    ]
